### ISSUE TITLE
make generates assignment.D, not D

### ISSUE THREAD

**Issue by taehwoi** [snu-sf-class/pl2016#12]
After running make, when I run P**.v on CoqIDE(and Coquille) it shows the following error

```
Error: The file /home/thoum/school/2016-1/pl/assignments/00/D.vo contains library
assignment.D and not library D
```

however when compiled with `coqc D.v`, P**.v runs smoothly.

**Comment by jeehoonkang** [comment]
Would you please post your Makefile?  Recently I fixed the Makefile (https://github.com/snu-sf-class/pl2016/blob/master/assignments/00/Makefile).

Check this line https://github.com/snu-sf-class/pl2016/blob/master/assignments/00/Makefile#L22

**Comment by taehwoi** [comment]
``` make
DFILES = D.v
PFILES = $(shell find P??.v)
EFILES = $(shell find E??.v)

POFILES = $(patsubst %.v,%.vo,$(PFILES))
EOFILES = $(patsubst %.v,%.vo,$(EFILES))

all: $(DFILES) $(PFILES) Makefile.coq
    $(MAKE) -f Makefile.coq $(POFILES)

eval: $(DFILES) $(PFILES) $(EFILES) Makefile.coq
    $(MAKE) -f Makefile.coq $(EOFILES)

%.vo: Makefile.coq
    $(MAKE) -f Makefile.coq "$@"

clean: Makefile.coq
    $(MAKE) -f Makefile.coq clean
    rm _CoqProject Makefile.coq

Makefile.coq: Makefile $(PFILES) $(EFILES)
    (echo "-R . assignment"; \
         echo $(DFILES) $(PFILES) $(EFILES)) > _CoqProject
    coq_makefile -f _CoqProject -o Makefile.coq
```

This is the Makefile I have but since I pulled this repository after the fix, I don't think there would be any difference.
GNU Make version is 3.81

**Comment by jeehoonkang** [comment]
Would you please `make clean` and then `make`?

**Comment by taehwoi** [comment]
The error is still occuring.
Since the error complained about assignment.D I tried `(echo "-R . "` and now it complains about library D.v.D.
I don't know much about Makefiles but maybe D.v should be compiled without any extra arguments..?

**Comment by jeehoonkang** [comment]
Would you please specify your environment?  OS, how Coq is installed, etc.

**Comment by taehwoi** [comment]
Ubuntu 14.10, ocaml 4.02.3 and coq 8.4pl5 installed via opam 1.2.2 .

**Comment by taehwoi** [comment]
I would like to note that this error only occurs with CoqIDE-ishs.
When running `make eval`, everything is fine.

**Comment by jeehoonkang** [comment]
I cannot reproduce this (CentOS 7, OCaml 4.02.3, Coq 8.4pl5 via opam)..  Would anyone please reproduce this, please?

**Comment by taehwoi** [comment]
It can be reproduced at the martini server (martini.snucse.org)

**Comment by swchoi06** [comment]
@jeehoonkang 
I got the same errors on MacOS 10.10.5, Coq 8.4pl6, OCaml 4.02.3, and vim as a IDE.

**Comment by swchoi06** [comment]
If I just remove

>   echo "-R . assignment"; \

part, then it works fine. 

However, I don't actually know what that part of the code is doing. 

Do you have any idea?

```
DFILES = D.v
PFILES = $(shell find P??.v)
EFILES = $(shell find E??.v)

POFILES = $(patsubst %.v,%.vo,$(PFILES))
EOFILES = $(patsubst %.v,%.vo,$(EFILES))

all: $(DFILES) $(PFILES) Makefile.coq
    $(MAKE) -f Makefile.coq $(POFILES)

eval: $(DFILES) $(PFILES) $(EFILES) Makefile.coq
    $(MAKE) -f Makefile.coq $(EOFILES)

%.vo: Makefile.coq
    $(MAKE) -f Makefile.coq "$@"

clean: Makefile.coq
    $(MAKE) -f Makefile.coq clean
    rm _CoqProject Makefile.coq

Makefile.coq: Makefile $(PFILES) $(EFILES)
    echo $(DFILES) $(PFILES) $(EFILES) > _CoqProject
    coq_makefile -f _CoqProject -o Makefile.coq
```

ps. becareful for the indents while editing Makefile

**Comment by jeehoonkang** [comment]
@swchoi06 I followed your advice (https://github.com/snu-sf-class/pl2016/commit/6b8ffea2dbac8d99cce26fe02540e4b29b9b9af4).  Would anyone please check if it works?  It worked fine for me.

**Comment by taehwoi** [comment]
Yes it is working fine now. @jeehoonkang @swchoi06  Thanks for your assistance!
